[2013-11-22 10:24:00,765][ERROR] UserDAO.py:[<module>]:32 (YYA) : [test error]
